pipelines:
  default:
    - step:
        name: Build and Deploy to Netlify
        caches:
          - node
        script:
          - npm install
          - npm run build:prod
          - npm install -g netlify-cli
          - netlify deploy --prod --dir=dist/lms-project/browser

definitions:
  caches:
    node: ~/.npm
